frase = 'Curso em Vídeo Python'
print(frase[::2])
print(frase.count('o'))
print(len(frase.strip()))
print(frase.replace('Python', 'Android'))
print(frase.lower().find('vídeo'))
print(frase.split())
print('><'.join(frase))
print(frase.capitalize())
print(frase.upper())
print(frase.lower())
print(frase.title())
print(frase.strip())
print(frase.rstrip())
